### PR TITLE
Change project structure to monorepo

### PR DESCRIPTION
**Pull request by escottalexander**
Moved all the existing server files into it's own directory to follow the typical monorepo pattern we see in BG projects.

This is a prerequisite for adding the DB.

### CODE REVIEW

**Comment by escottalexander** [comment]
@MattPereira No need to look into this deeply. I would just make sure you can still run the server after getting my changes.

**Review by MattPereira — CHANGES_REQUESTED** [review]
:100: moving to monorepo structure is a great call

tested result of the endpoint included in the README
image
 
 The paths being used to reach into the `challenges/` folder are currently setup as relative so they either gotta be adjusted to account for new monorepo structure or refactored into absolute paths

**Comment by escottalexander** [comment]
Good catch. I fixed the paths and it should work now.

**Review by MattPereira — APPROVED** [review]
I like the move to consolidate env vars into single file parked in monorepo's root directory :ok_hand:

**Pull request merged**
